package graph

import (
	"context"
	"main/graph/model"
)

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }

// UpdateArtistaGenero implements [MutationResolver].
func (r *mutationResolver) UpdateArtistaGenero(ctx context.Context, input model.UpdateArtistaGenero) (*model.ArtistaGenero, error) {
	panic("unimplemented")
}

type queryResolver struct{ *Resolver }

// FindArtistaGeneroByArtista implements [QueryResolver].
func (r *queryResolver) FindArtistaGeneroByArtista(ctx context.Context, idArtista string) ([]*model.ArtistaGenero, error) {
	panic("unimplemented")
}

// FindMembresiasByCliente implements [QueryResolver].
func (r *queryResolver) FindMembresiasByCliente(ctx context.Context, idCliente string) ([]*model.Membresia, error) {
	panic("unimplemented")
}

// FindMembresiasByTarjeta implements [QueryResolver].
func (r *queryResolver) FindMembresiasByTarjeta(ctx context.Context, idTarjeta string) ([]*model.Membresia, error) {
	panic("unimplemented")
}

// GetObra implements [QueryResolver].
func (r *queryResolver) GetObra(ctx context.Context, id string) (*model.Obra, error) {
	panic("unimplemented")
}
