// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Artista struct {
	ID              string `json:"id"`
	Nombre          string `json:"nombre"`
	FechaNacimiento string `json:"fecha_nacimiento"`
	Nacionalidad    string `json:"nacionalidad"`
	Biografia       string `json:"biografia"`
	Foto            string `json:"foto"`
}

type ArtistaGenero struct {
	IDArtista string   `json:"id_artista"`
	Artista   *Artista `json:"artista"`
	IDGenero  string   `json:"id_genero"`
	Genero    *Genero  `json:"genero"`
}

type Cliente struct {
	ID              string `json:"id"`
	Nombre          string `json:"nombre"`
	Email           string `json:"email"`
	Telefono        string `json:"telefono"`
	Login           string `json:"login"`
	Password        string `json:"password"`
	CodigoSeguridad string `json:"codigo_seguridad"`
}

type Genero struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
}

type LoginResponseCliente struct {
	Success bool    `json:"success"`
	ID      *string `json:"id,omitempty"`
	Nombre  *string `json:"nombre,omitempty"`
}

type LoginResponseTrabajador struct {
	Success bool    `json:"success"`
	ID      *string `json:"id,omitempty"`
	Nombre  *string `json:"nombre,omitempty"`
	Admin   *bool   `json:"admin,omitempty"`
}

type Membresia struct {
	IDMembresia string          `json:"id_membresia"`
	IDCliente   string          `json:"id_cliente"`
	Cliente     *Cliente        `json:"cliente"`
	IDTarjeta   string          `json:"id_tarjeta"`
	Tarjeta     *TarjetaCliente `json:"tarjeta"`
	Fecha       string          `json:"fecha"`
}

type Mutation struct {
}

type NewArtista struct {
	Nombre          string `json:"nombre"`
	FechaNacimiento string `json:"fecha_nacimiento"`
	Nacionalidad    string `json:"nacionalidad"`
	Biografia       string `json:"biografia"`
	Foto            string `json:"foto"`
}

type NewArtistaGenero struct {
	IDArtista string `json:"id_artista"`
	IDGenero  string `json:"id_genero"`
}

type NewCliente struct {
	Nombre          string `json:"nombre"`
	Email           string `json:"email"`
	Telefono        string `json:"telefono"`
	Login           string `json:"login"`
	Password        string `json:"password"`
	CodigoSeguridad string `json:"codigo_seguridad"`
}

type NewGenero struct {
	Nombre string `json:"nombre"`
}

type NewMembresia struct {
	IDCliente string `json:"id_cliente"`
	IDTarjeta string `json:"id_tarjeta"`
	Fecha     string `json:"fecha"`
}

type NewObra struct {
	Nombre        string     `json:"nombre"`
	IDArtista     string     `json:"id_artista"`
	IDGenero      string     `json:"id_genero"`
	Precio        int32      `json:"precio"`
	FechaCreacion string     `json:"fecha_creacion"`
	Status        StatusObra `json:"status"`
	Foto          string     `json:"foto"`
	Material      string     `json:"material"`
	Peso          int32      `json:"peso"`
	Dimensiones   string     `json:"dimensiones"`
}

type NewOrden struct {
	IDObra       string      `json:"id_obra"`
	IDCliente    string      `json:"id_cliente"`
	IDTrabajador *string     `json:"id_trabajador,omitempty"`
	Fecha        string      `json:"fecha"`
	Status       StatusOrden `json:"status"`
}

type NewPreguntas struct {
	IDCliente string `json:"id_cliente"`
	Pregunta  string `json:"pregunta"`
	Respuesta string `json:"respuesta"`
}

type NewTarjetaCliente struct {
	IDCliente     string `json:"id_cliente"`
	NumeroTarjeta string `json:"numero_tarjeta"`
	Tipo          string `json:"tipo"`
}

type NewTrabajador struct {
	Nombre   string `json:"nombre"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}

type Obra struct {
	ID            string     `json:"id"`
	Nombre        string     `json:"nombre"`
	IDArtista     string     `json:"id_artista"`
	Artista       *Artista   `json:"artista"`
	IDGenero      string     `json:"id_genero"`
	Genero        *Genero    `json:"genero"`
	Precio        int32      `json:"precio"`
	FechaCreacion string     `json:"fecha_creacion"`
	Status        StatusObra `json:"status"`
	Foto          string     `json:"foto"`
	Material      string     `json:"material"`
	Peso          int32      `json:"peso"`
	Dimensiones   string     `json:"dimensiones"`
}

type Orden struct {
	ID           string      `json:"id"`
	IDObra       string      `json:"id_obra"`
	Obra         *Obra       `json:"obra"`
	IDCliente    string      `json:"id_cliente"`
	Cliente      *Cliente    `json:"cliente"`
	IDTrabajador string      `json:"id_trabajador"`
	Trabajador   *Trabajador `json:"trabajador"`
	Fecha        string      `json:"fecha"`
	Status       StatusOrden `json:"status"`
}

type Preguntas struct {
	ID        string   `json:"id"`
	IDCliente string   `json:"id_cliente"`
	Cliente   *Cliente `json:"cliente"`
	Pregunta  string   `json:"pregunta"`
	Respuesta string   `json:"respuesta"`
}

type Query struct {
}

type TarjetaCliente struct {
	IDTarjeta     string   `json:"id_tarjeta"`
	IDCliente     string   `json:"id_cliente"`
	Cliente       *Cliente `json:"cliente"`
	NumeroTarjeta string   `json:"numero_tarjeta"`
	Tipo          string   `json:"tipo"`
}

type Trabajador struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}

type UpdateArtista struct {
	ID              string  `json:"id"`
	Nombre          *string `json:"nombre,omitempty"`
	FechaNacimiento *string `json:"fecha_nacimiento,omitempty"`
	Nacionalidad    *string `json:"nacionalidad,omitempty"`
	Biografia       *string `json:"biografia,omitempty"`
	Foto            *string `json:"foto,omitempty"`
}

type UpdateArtistaGenero struct {
	IDArtista      string  `json:"id_artista"`
	IDGenero       string  `json:"id_genero"`
	NuevoIDArtista *string `json:"nuevo_id_artista,omitempty"`
	NuevoIDGenero  *string `json:"nuevo_id_genero,omitempty"`
}

type UpdateCliente struct {
	ID              string  `json:"id"`
	Nombre          *string `json:"nombre,omitempty"`
	Email           *string `json:"email,omitempty"`
	Telefono        *string `json:"telefono,omitempty"`
	Login           *string `json:"login,omitempty"`
	Password        *string `json:"password,omitempty"`
	CodigoSeguridad *string `json:"codigo_seguridad,omitempty"`
}

type UpdateGenero struct {
	ID     string  `json:"id"`
	Nombre *string `json:"nombre,omitempty"`
}

type UpdateMembresia struct {
	IDMembresia string  `json:"id_membresia"`
	IDCliente   *string `json:"id_cliente,omitempty"`
	IDTarjeta   *string `json:"id_tarjeta,omitempty"`
	Fecha       *string `json:"fecha,omitempty"`
}

type UpdateObra struct {
	ID            string      `json:"id"`
	Nombre        *string     `json:"nombre,omitempty"`
	IDArtista     *string     `json:"id_artista,omitempty"`
	IDGenero      *string     `json:"id_genero,omitempty"`
	Precio        *int32      `json:"precio,omitempty"`
	FechaCreacion *string     `json:"fecha_creacion,omitempty"`
	Status        *StatusObra `json:"status,omitempty"`
	Foto          *string     `json:"foto,omitempty"`
	Material      *string     `json:"material,omitempty"`
	Peso          *int32      `json:"peso,omitempty"`
	Dimensiones   *string     `json:"dimensiones,omitempty"`
}

type UpdateOrden struct {
	ID           string       `json:"id"`
	IDObra       *string      `json:"id_obra,omitempty"`
	IDCliente    *string      `json:"id_cliente,omitempty"`
	IDTrabajador *string      `json:"id_trabajador,omitempty"`
	Fecha        *string      `json:"fecha,omitempty"`
	Status       *StatusOrden `json:"status,omitempty"`
}

type UpdatePreguntas struct {
	ID        string  `json:"id"`
	IDCliente *string `json:"id_cliente,omitempty"`
	Pregunta  *string `json:"pregunta,omitempty"`
	Respuesta *string `json:"respuesta,omitempty"`
}

type UpdateTarjetaCliente struct {
	IDTarjeta     string  `json:"id_tarjeta"`
	IDCliente     *string `json:"id_cliente,omitempty"`
	NumeroTarjeta *string `json:"numero_tarjeta,omitempty"`
	Tipo          *string `json:"tipo,omitempty"`
}

type UpdateTrabajador struct {
	ID       string  `json:"id"`
	Nombre   *string `json:"nombre,omitempty"`
	Login    *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
	Admin    *bool   `json:"admin,omitempty"`
}

type StatusObra string

const (
	StatusObraDisponible StatusObra = "DISPONIBLE"
	StatusObraReservada  StatusObra = "RESERVADA"
	StatusObraVendida    StatusObra = "VENDIDA"
)

var AllStatusObra = []StatusObra{
	StatusObraDisponible,
	StatusObraReservada,
	StatusObraVendida,
}

func (e StatusObra) IsValid() bool {
	switch e {
	case StatusObraDisponible, StatusObraReservada, StatusObraVendida:
		return true
	}
	return false
}

func (e StatusObra) String() string {
	return string(e)
}

func (e *StatusObra) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StatusObra(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StatusObra", str)
	}
	return nil
}

func (e StatusObra) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StatusObra) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StatusObra) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StatusOrden string

const (
	StatusOrdenPendiente  StatusOrden = "PENDIENTE"
	StatusOrdenConcretada StatusOrden = "CONCRETADA"
	StatusOrdenCancelada  StatusOrden = "CANCELADA"
)

var AllStatusOrden = []StatusOrden{
	StatusOrdenPendiente,
	StatusOrdenConcretada,
	StatusOrdenCancelada,
}

func (e StatusOrden) IsValid() bool {
	switch e {
	case StatusOrdenPendiente, StatusOrdenConcretada, StatusOrdenCancelada:
		return true
	}
	return false
}

func (e StatusOrden) String() string {
	return string(e)
}

func (e *StatusOrden) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StatusOrden(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StatusOrden", str)
	}
	return nil
}

func (e StatusOrden) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StatusOrden) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StatusOrden) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
