// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cliente struct {
	ID              string `json:"id_cliente"`
	Nombre          string `json:"nombre"`
	Email           string `json:"email"`
	Telefono        string `json:"telefono"`
	Login           string `json:"login"`
	Password        string `json:"password"`
	CodigoSeguridad string `json:"codigo_seguridad"`
}

type Genero struct {
	ID     string `json:"id_genero"`
	Nombre string `json:"nombre"`
}

type Mutation struct {
}

type NewCliente struct {
	Nombre          string `json:"nombre"`
	Email           string `json:"email"`
	Telefono        string `json:"telefono"`
	Login           string `json:"login"`
	Password        string `json:"password"`
	CodigoSeguridad string `json:"codigo_seguridad"`
}

type NewGenero struct {
	Nombre string `json:"nombre"`
}

type NewObra struct {
	Nombre        string `json:"nombre"`
	IDArtista     string `json:"id_artista"`
	IDGenero      string `json:"id_genero"`
	Precio        int32  `json:"precio"`
	FechaCreacion string `json:"fecha_creacion"`
	Status        string `json:"status"`
	Foto          string `json:"foto"`
	Material      string `json:"material"`
	Peso          int32  `json:"peso"`
	Dimensiones   string `json:"dimensiones"`
}

type NewTrabajador struct {
	Nombre   string `json:"nombre"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}

type Obra struct {
	ID            string `json:"id_obra"`
	Nombre        string `json:"nombre"`
	IDArtista     string `json:"id_artista"`
	IDGenero      string `json:"id_genero"`
	Precio        int32  `json:"precio"`
	FechaCreacion string `json:"fecha_creacion"`
	Status        string `json:"status"`
	Foto          string `json:"foto"`
	Material      string `json:"material"`
	Peso          int32  `json:"peso"`
	Dimensiones   string `json:"dimensiones"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Trabajador struct {
	ID       string `json:"id_trabajador"`
	Nombre   string `json:"nombre"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
}

type UpdateCliente struct {
	ID              string  `json:"id_cliente"`
	Nombre          *string `json:"nombre,omitempty"`
	Email           *string `json:"email,omitempty"`
	Telefono        *string `json:"telefono,omitempty"`
	Login           *string `json:"login,omitempty"`
	Password        *string `json:"password,omitempty"`
	CodigoSeguridad *string `json:"codigo_seguridad,omitempty"`
}

type UpdateGenero struct {
	ID     string  `json:"id_genero"`
	Nombre *string `json:"nombre,omitempty"`
}

type UpdateObra struct {
	ID            string  `json:"id_obra"`
	Nombre        *string `json:"nombre,omitempty"`
	IDArtista     *string `json:"id_artista,omitempty"`
	IDGenero      *string `json:"id_genero,omitempty"`
	Precio        *int32  `json:"precio,omitempty"`
	FechaCreacion *string `json:"fecha_creacion,omitempty"`
	Status        *string `json:"status,omitempty"`
	Foto          *string `json:"foto,omitempty"`
	Material      *string `json:"material,omitempty"`
	Peso          *int32  `json:"peso,omitempty"`
	Dimensiones   *string `json:"dimensiones,omitempty"`
}

type UpdateTrabajador struct {
	ID       string  `json:"id_trabajador"`
	Nombre   *string `json:"nombre,omitempty"`
	Login    *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
	Admin    *bool   `json:"admin,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
